/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.ChamCongController;
import java.sql.Time;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BangLuong;
import model.CaLamViec;
import model.NhanVien;

/**
 *
 * @author HoaiNam
 */
public class ChamCongFrm extends javax.swing.JFrame {

    /**
     * Creates new form ChamCongFrm
     */
    private NhanVien nhanVien;
    private DefaultTableModel modelBC;
    private float total = 0;
    private static BangLuong bangLuong;

    public ChamCongFrm(NhanVien nhanVien) {
        this.nhanVien = nhanVien;
        initComponents();

        modelBC = (DefaultTableModel) tblBangCong.getModel();
        int nhanVienID = nhanVien.getId();
        int week = this.getWeekCurrent();

        // Load data NhanVien.
        labNameNV.setText(nhanVien.getName());
        labAgeNV.setText(nhanVien.getAge() + "");
        labSpecNV.setText(nhanVien.getSpecialize());

        labWeek_1.setText("Tuần : " + this.getWeekCurrent() + "");
        labWeek.setText(this.getWeekCurrent() + "");

        ChamCongController chamCong = new ChamCongController();

        bangLuong = chamCong.getByWeekAndIdNV(nhanVienID, week);

        if (bangLuong == null) {
            bangLuong = new BangLuong();
            JOptionPane.showMessageDialog(rootPane, "Không tồn tại dữ liệu !");
            this.setVisible(false);
            btnThanhToan.setEnabled(false);
            return;
        }
        loadData(bangLuong.getDsCalamViec());

        labTotal.setText(this.total + "");

        String isActiveText = "";

        if (bangLuong.isPaid()) {
            isActiveText = "Đã thanh toán";
            btnThanhToan.setEnabled(false);
        } else {
            isActiveText = "Chưa thanh toán";
        }

        labActive.setText(isActiveText);

        checkedData(this.total, bangLuong.getPaymentAmount());
    }

    public void checkedData(float total1, float total2) {
        if (total1 != total2) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi dữ liệu sai lệch !");
        }
    }

    public void loadData(ArrayList<CaLamViec> dsCLV) {
        while (modelBC.getRowCount() > 0) {
            modelBC.removeRow(0);
        }

        int i = 1;

        for (CaLamViec clv : dsCLV) {
            modelBC.addRow(new Object[]{
                i++,
                clv.getCaKham().getDay(),
                clv.getCaKham().getShift(),
                this.CountSoGioLam(clv.getCheckIn(), clv.getCheckOut()),
                this.nhanVien.getPriceUnit(),
                this.countMoney(this.CountSoGioLam(clv.getCheckIn(), clv.getCheckOut()), this.nhanVien.getPriceUnit()),});
        }
    }

    private float countMoney(float CountSoGioLam, float priceUnit) {
        float totalRow = CountSoGioLam * priceUnit;
        this.total += totalRow;
        return totalRow;
    }

    private static int toMins(String s) {
        String[] hourMin = s.split(":");
        int hour = Integer.parseInt(hourMin[0]);
        int mins = Integer.parseInt(hourMin[1]);
        int hoursInMins = hour * 60;
        return hoursInMins + mins;
    }

    private float CountSoGioLam(Time checkIn, Time checkOut) {
        return (float) Math.round((float) (toMins(checkOut.toString()) - toMins(checkIn.toString())) / 60 * 10) / 10;
    }

    public int getWeekCurrent() {
        Date day = new Date();
        return getWeekByDate(day);
    }

    public int getWeekByDate(Date day) {
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(day);
        System.out.println(calendar.get(Calendar.SATURDAY));
        return calendar.get(Calendar.WEEK_OF_YEAR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        labTitle = new javax.swing.JLabel();
        labWeek_1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangCong = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        labTitleTotal = new javax.swing.JLabel();
        labTotal = new javax.swing.JLabel();
        labTitleWeek = new javax.swing.JLabel();
        labWeek = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labTitalActive = new javax.swing.JLabel();
        labActive = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        btnInHoaDon = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labTitleAgeNV = new javax.swing.JLabel();
        labTitleNameNV = new javax.swing.JLabel();
        labTitleSpecNV = new javax.swing.JLabel();
        labNameNV = new javax.swing.JLabel();
        labAgeNV = new javax.swing.JLabel();
        labSpecNV = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labTitle.setText("Bảng công");

        labWeek_1.setText("Tuần : 35");

        tblBangCong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Ngày", "Buổi (Ca)", "Số giờ làm", "Đơn giá làm", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(tblBangCong);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tổng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        labTitleTotal.setText("Tổng tiền công : ");

        labTotal.setText("5000000");

        labTitleWeek.setText("Tuần : ");

        labWeek.setText("35");

        jLabel9.setText("VND");

        labTitalActive.setText("Trạng thái : ");

        labActive.setText("Đã thanh toán");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labTitleTotal)
                    .addComponent(labTitleWeek)
                    .addComponent(labTitalActive))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labActive)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labWeek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTitleWeek)
                    .addComponent(labWeek))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTitleTotal)
                    .addComponent(labTotal)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTitalActive)
                    .addComponent(labActive))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnThanhToan.setText("Thanh toán tiền công");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnInHoaDon.setText("In hóa đơn");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin Bác sĩ /Y tá", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        labTitleAgeNV.setText("Tuổi : ");

        labTitleNameNV.setText("Tên : ");

        labTitleSpecNV.setText("Chuyên Khoa : ");

        labNameNV.setText("Vũ Hoài Nam");

        labAgeNV.setText("25");

        labSpecNV.setText("Tai Muii Hong");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labTitleSpecNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labSpecNV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labTitleNameNV)
                            .addComponent(labTitleAgeNV))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labAgeNV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labNameNV, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(70, 70, 70))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTitleNameNV)
                    .addComponent(labNameNV))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTitleAgeNV)
                    .addComponent(labAgeNV))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labTitleSpecNV)
                    .addComponent(labSpecNV, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThanhToan)
                    .addComponent(btnInHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labWeek_1))
                    .addComponent(labTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labWeek_1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        XacNhanFrm xacNhan = new XacNhanFrm(bangLuong);
        xacNhan.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnThanhToanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChamCongFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChamCongFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChamCongFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChamCongFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChamCongFrm(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInHoaDon;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labActive;
    private javax.swing.JLabel labAgeNV;
    private javax.swing.JLabel labNameNV;
    private javax.swing.JLabel labSpecNV;
    private javax.swing.JLabel labTitalActive;
    private javax.swing.JLabel labTitle;
    private javax.swing.JLabel labTitleAgeNV;
    private javax.swing.JLabel labTitleNameNV;
    private javax.swing.JLabel labTitleSpecNV;
    private javax.swing.JLabel labTitleTotal;
    private javax.swing.JLabel labTitleWeek;
    private javax.swing.JLabel labTotal;
    private javax.swing.JLabel labWeek;
    private javax.swing.JLabel labWeek_1;
    private javax.swing.JTable tblBangCong;
    // End of variables declaration//GEN-END:variables

}
