/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.XacNhanController;
import java.sql.Time;
import java.util.Date;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import model.BangLuong;
import model.NhanVien;

/**
 *
 * @author HoaiNam
 */
public class XacNhanFrm extends javax.swing.JFrame {

    /**
     * Creates new form XacNhanFrm
     */
    private static int seconds = 10;
    private static int minutes = 2;
    private static Timer timer;
    private static NhanVien nhanVien;
    private static BangLuong bangLuong;
    private static String otpCode;

    public static String getOtpCode() {
        return otpCode;
    }

    public static void setOtpCode(String otpCode) {
        XacNhanFrm.otpCode = otpCode;
    }

    public XacNhanFrm(BangLuong bangLuong) {
        initComponents();
        this.nhanVien = bangLuong.getNhanVien();
        this.bangLuong = bangLuong;
        this.generateCode(nhanVien.getPhone());
        if (nhanVien.getPhone().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(rootPane, "Thiếu dữ liệu ! yêu cầu cập nhập số điện thoại của bác sỹ/y tá");
        }
    }

    public static String OTP(int len, String numbers) {

        Random rndm_method = new Random();

        String otp = "";

        for (int i = 0; i < len; i++) {
            otp += numbers.charAt(rndm_method.nextInt(numbers.length()));
        }

        return otp;
    }

    private void generateCode(String phone) {
        this.otpCode = OTP(4, phone);
        System.out.println(this.otpCode);
        runTimer();
    }

    public void runTimer() {
        timer = new Timer();

        Time time = new Time(0, minutes, seconds);
        TimerTask task = new TimerTask() {
            public void run() {
                labTimer.setText(time.getMinutes() + ":" + time.getSeconds());
                if (seconds == 0 && minutes == 0) {
                    timer.cancel();
                    setOtpCode("");
                    JOptionPane.showMessageDialog(rootPane, "Giao dịch không thành công !");
                }
                if (seconds == 0) {
                    seconds = 60;
                    minutes--;
                }
                time.setMinutes(minutes);
                time.setSeconds(seconds);
                seconds--;
            }
        };
        timer.scheduleAtFixedRate(task, 1000, 1000);
    }

    private void updateInfo() {
        this.bangLuong.setPaid(true);
        Date date = new Date(); 
        this.bangLuong.setPaymentDate(date);
        XacNhanController xacNhan = new XacNhanController();
        if (!xacNhan.updateInfo(this.bangLuong)) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi cập nhập dữ liệu !");
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labTitle = new javax.swing.JLabel();
        labTimer = new javax.swing.JLabel();
        txtMaXN = new javax.swing.JTextField();
        btnXacNhan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labTitle.setText("Nhập mã OTP");

        labTimer.setText("00:00");

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        jLabel1.setText("Một mã OTP đã được gửi tới số điện thoại của bác sĩ / y tá");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(labTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaXN, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(labTimer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(labTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(labTimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMaXN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        String otpInput = txtMaXN.getText();
        if (otpInput.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(rootPane, "Input rỗng");
        } else if (otpInput.equalsIgnoreCase(this.otpCode)) {
            timer.cancel();
            setOtpCode("");
            updateInfo();
            JOptionPane.showMessageDialog(rootPane, "Giao dịch thành công !");
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Mã OTP không hợp lệ !");
        }
    }//GEN-LAST:event_btnXacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XacNhanFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XacNhanFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XacNhanFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XacNhanFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XacNhanFrm(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labTimer;
    private javax.swing.JLabel labTitle;
    private javax.swing.JTextField txtMaXN;
    // End of variables declaration//GEN-END:variables

}
